# This workflow integrates ShiftLeft Scan with GitHub's code scanning feature
# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# Visit https://slscan.io/en/latest/integrations/github-actions/ for help
name: ShiftLeft Scan

on:
    push:
    pull_request:
    workflow_dispatch:


jobs:
    Shifleft:
        name: Shiftleft
        runs-on: ubuntu-latest
        steps:
            - name: Perform ShiftLeft Scan
              uses: actions/checkout@v1


            - name: Scan code with Shiftleft
              uses: docker://shiftleft/sast-scan
              #uses: ShiftLeftSecurity/sast-scan@master
              #uses: ShiftLeftSecurity/scan-action@master
              with:
                  type: "php"
                  output: reports
