# This workflow integrates ShiftLeft Scan with GitHub's code scanning feature
# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# Visit https://slscan.io/en/latest/integrations/github-actions/ for help
name: ShiftLeft Scan

on:
    push:
    pull_request:
    workflow_dispatch:


jobs:
    Shifleft:
        name: Shiftleft
        runs-on: ubuntu-latest
        steps:
            - name: Perform ShiftLeft Scan
              uses: actions/checkout@v1


            - name: Scan code with Shiftleft
              uses: ShiftLeftSecurity/scan-action@master
              env:
                  WORKSPACE: ""
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SCAN_AUTO_BUILD: true

              with:
                  output: reports
                  type: php
                  # type: credscan,java,plsql,php,nodejs,depscan,php

            - name: Upload report



  uses: actions/upload-artifact@v1.0.0
  with:
    name: shiftleft-scan-reports
    path: reports
