# This workflow integrates ShiftLeft Scan with GitHub's code scanning feature
# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# Visit https://slscan.io/en/latest/integrations/github-actions/ for help
name: ShiftLeft Scan

on:
    push:

jobs:
    Shifleft:
        name: Shiftleft
        runs-on: ubuntu-latest
        steps:
            - name: Perform ShiftLeft Scan
              uses: actions/checkout@v1


            - name: Scan code with Shiftleft
              uses: ShiftLeftSecurity/scan-action@master
              env:
                  WORKSPACE: ""
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SCAN_AUTO_BUILD: true


            - name: Upload results to Github 
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: results.sarif
